### ISSUE TITLE
v1.3.0 not working

### ISSUE THREAD

**Issue by Psycarlo** [nuxt/image#1227] opened 2024-01-31 16:00 UTC
Version 1.3.0 does not work for me.

Replicate:

`
pnpm dlx nuxi@latest init .
pnpm add @nuxt/image
`

Add to modules.

When I run the server, the image does not show.

It works with v1.2.0...

**Comment by MateThemes** [comment] 2024-02-01 15:00
I have the same error

**Comment by riobahtiar** [comment] 2024-02-01 20:04
This issue seems to be related or duplicated to the previous issue. For workaround and temporary update you can see #1210. Thanks

**Comment by szvest** [comment] 2024-02-01 20:10
I believe that happens because sharp requires at least node 18.17.0 as it says [here](https://sharp.pixelplumbing.com/). Check your node version.

**Comment by szvest** [comment] 2024-02-01 20:13
> Reference

I believe that happens because sharp requires at least node 18.17.0 as it says [here](https://sharp.pixelplumbing.com/). Check your node version.

**Comment by ThePlastic** [comment] 2024-02-02 08:16
+1

**Comment by manniL** [comment] 2024-02-02 09:30
Duplicate of https://github.com/nuxt/image/issues/1210

**Closed by manniL** 2024-02-02 09:30 UTC

**Comment by MateThemes** [comment] 2024-02-02 09:50
> I believe that happens because sharp requires at least node 18.17.0 as it says [here](https://sharp.pixelplumbing.com/). Check your node version.

I have node version +21 and have the same problem

**Comment by chasebank** [comment] 2024-02-05 01:56
I updated Yarn and this finally went away, even without locking the version.

Yarn 4.1.0
Node 20.11.0

**Comment by G3Raven** [comment] 2024-12-17 20:01
do this, it worked for me
in package.json
```json
"overrides": {
    "sharp": "0.32.6"
}
``` 

```shell
npm remove sharp && npm update
```
