### ISSUE TITLE
Why can't the browser display images correctly?Display 500 (Internal Server Error)

### ISSUE THREAD

**Issue by myskylq** [nuxt/image#1034] opened 2023-10-06 14:20 UTC
Hi,
I followed the official documentation step by step.But the image cannot be displayed using <NuxtImg>

# 1. package.json
```
"devDependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.7.4",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@nuxt/image": "1.0.0-rc.3",
  }
```

# 2.nuxt.config.ts
```
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxt/image'],
})
```

# 3.Put an image(1.jpg) into the "/public/images" directory

# 4.Use <NuxtImg> in the page
```
<template>
    <div>
        <NuxtImg src="/images/1.jpg" />
        <img src="/images/1.jpg" alt="" srcset="">
    </div>
</template>
```

# 5.After starting the project, the picture cannot be displayed
<img> can be displayed，The console reports an error:GET http://localhost:3001/_ipx/_/images/1.jpg 500 (Internal Server Error)，Is that why? Did I configure it incorrectly?

**Comment by yk-sgr** [comment] 2023-10-13 18:42
Edge Channel works for me

**Comment by myskylq** [comment] 2023-10-20 16:01
**I reinstalled Nuxt 3.8 and the Images module, but encountered an error during installation:** 

"node_modules/.pnpm/sharp@0.32.6/node_modules/sharp: Running install script, failed in 19.8s (skipped as optional)".

**After installation, I added a picture using <NuxtImg>, but an error occurred in the browser console:**

"[500] [IPX_ERROR] Something went wrong installing the "sharp" module
Cannot find module '../build/Release/sharp-win32-x64.node'
Require stack:
- E:\CodeExec\testPro\test-nuxt3.8-01\node_modules\.pnpm\sharp@0.32.6\node_modules\sharp\lib\sharp.js
- E:\CodeExec\testPro\test-nuxt3.8-01\node_modules\.pnpm\sharp@0.32.6\node_modules\sharp\lib\constructor.js
- E:\CodeExec\testPro\test-nuxt3.8-01\node_modules\.pnpm\sharp@0.32.6\node_modules\sharp\lib\index.js
- Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install"

**Why did the installation go wrong?What should I do?**

**Comment by Thevetat** [comment] 2023-10-24 08:54
https://stackblitz.com/edit/nuxt-starter-y3znyg?file=app.vue

The same thing is happening to me, minimal reproduction above.  I have not tried the edge channel yet, I will in the AM.

**Comment by Thevetat** [comment] 2023-10-24 09:25
@myskylq Opting in to the edge channel fixed it for me.  I had the same errors as you.

https://image.nuxt.com/get-started/installation#opting-into-the-edge-channel

**Comment by asteof** [comment] 2024-01-23 19:44
So I stubled across the same problem and created [small repo for reprodution purposes](https://github.com/asteof/nuxt-image-ipx-internal-serve-error-bug).
In my case npm installation worked fine, but yarn did not, the error persists GET http://localhost:3001/_ipx/_/images/1.jpg 500 (Internal Server Error)

And what I've found is that there is no `_ipx` forder in sources tab of browser devtools.
Hope to see some comments on this issue.

**Comment by roadtosixx** [comment] 2024-02-18 18:59
Same problem, strange on my PC everything works, but on my Laptop ( nuxt dev mode ) the picture does not load.

Same error as @myskylq

**Comment by sraff** [comment] 2024-02-28 14:44
Same issue fixed enabling the `inject` into `nuxt.config.ts` ?
``` 
export default defineNuxtConfig({
  image: {
    inject: true
  },
  modules: ['@nuxt/image'],
})
```

**Comment by aerophobic** [comment] 2024-02-29 12:38
Using `@nuxt/image@1.3.0`.

I had a similar issue getting 500 errros loading images with default provider `ipx`. looking into the actual response of the server route it stated:

```plaintext
"[500] [IPX_ERROR] Could not load the \"sharp\" module using the linux-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install"
```

So it turned out the platform specific sharp library was not installed. I removed the `@nuxt/image` package and readded it with:

```bash
yarn add @nuxt/image --ignore-engines
```

Everything worked well then. Maybe this helps someone struggling with the same issue.

**Comment by Gonzalo-Bruna** [comment] 2024-03-03 21:46
so I had the same issue, but solved it by removing the pnpm-lock file and then running the `pnpm install` command. (I am using `pnpm` as my package manager). It definitely had to do with the sharp package since this is what it showed:

```powershell
Downloading registry.npmjs.org/@img/sharp-win32-x64/0.33.2: 8.15 MB/8.15 MB, done
Packages: +6
++++++
Progress: resolved 1182, reused 1088, downloaded 8, added 6, done
node_modules/.pnpm/sharp@0.33.2/node_modules/sharp: Running install script, done in 78ms
```

**Comment by danielroe** [comment] 2024-04-22 16:43
It looks like this is an issue with `sharp` which should be resolved in the latest release. Closing for now, but please feel free to open a new issue with a reproduction if you still encounter this.

**Closed by danielroe** 2024-04-22 16:43 UTC
Labels: needs reproduction

**Comment by ItaloCanturil** [comment] 2025-02-12 14:02
I had the same issue, but it was not solved, I made all inside this issue but the image doesn't load in the browser.

**Comment by swunderlich** [comment] 2025-03-16 16:14
I came accross https://pnpm.io/package_json#pnpmsupportedarchitectures and used https://pnpm.io/package_json#pnpmsupportedarchitectures. 

```
pnpm approve-builds

✔ Choose which packages to build (Press <space> to select, <a> to toggle all, <i> to invert selection) · sharp

✔ The next packages will now be built: sharp.

Do you approve? (y/N) · true
node_modules/.pnpm/sharp@0.32.6/node_modules/sharp: Running install script, done in 4.9s
```

After that my local dev server worked again
