### ISSUE TITLE
Nuxt Image Cloudflare Provider Serious Bug

### ISSUE THREAD

**Issue by nafiz6629** [nuxt/image#1544] opened 2024-10-15 13:07 UTC
https://image.nuxt.com/providers/cloudflare#options 
In this Documentation there is written "/cdn-cgi/image/" will be automatically appended for generating URLs , Which is wrong. Proper prefix that should be appended is "/cdn-cgi/imagedelivery/" (reference: https://developers.cloudflare.com/images/manage-images/serve-images/serve-from-custom-domains/#custom-paths ) 
Please Fix This Bug

**Comment by masud-ictlayer** [comment] 2024-10-15 13:09
We also fetching same problem

**Comment by atiflayer** [comment] 2024-10-15 13:11
I faced the same issue too. Please fix this problem asap. Thank you!

**Comment by ictLayerPulock** [comment] 2024-10-15 13:13
I encountered the same issue as well. Kindly resolve this problem as soon as possible. Thank you!

**Comment by oritwoen** [comment] 2024-10-15 13:27
This is not a bug nor a problem.

- `/cdn-cgi/image/` and `/cdn-cgi/imagedelivery/` are two different services.

Everything working correctly with `/cdn-cgi/image/`

**Comment by ICTLAYER** [comment] 2024-10-15 14:19
> This is not a bug nor a problem.
> 
> * `/cdn-cgi/image/` and `/cdn-cgi/imagedelivery/` are two different services.
> 
> Everything working correctly with `/cdn-cgi/image/`

I also agree with you, BUT as per documentation [  /cdn-cgi/image/  ] isn't working. 

So please I need more elaborate documentation. Could you give us a more step-by-step guide?

Please check the reference: 

https://developers.cloudflare.com/images/manage-images/serve-images/serve-from-custom-domains/

https://developers.cloudflare.com/images/transform-images/transform-via-url/

**Comment by ICTLAYER** [comment] 2024-10-15 18:16
> > This is not a bug nor a problem.
> > 
> > * `/cdn-cgi/image/` and `/cdn-cgi/imagedelivery/` are two different services.
> > 
> > Everything working correctly with `/cdn-cgi/image/`
> 
> I also agree with you, BUT as per documentation [ /cdn-cgi/image/ ] isn't working.
> 
> So please I need more elaborate documentation. Could you give us a more step-by-step guide?
> 
> Please check the reference:
> 
> https://developers.cloudflare.com/images/manage-images/serve-images/serve-from-custom-domains/
> 
> https://developers.cloudflare.com/images/transform-images/transform-via-url/

More as example to prove myself:

Not Working:  https://nuxtimgtest.pages.dev/cdn-cgi/image/7mnVjFJmJT6C1-RIIlFtQg/cf0cac91-0a0e-4c86-c376-60597e37e700/public

Working:  https://nuxtimgtest.pages.dev/cdn-cgi/imagedelivery/7mnVjFJmJT6C1-RIIlFtQg/cf0cac91-0a0e-4c86-c376-60597e37e700/public

**Comment by phi0411141** [comment] 2024-11-13 03:16
It's a bit confusing but let me clarify, Cloudflare has 2 image services
- Transform on the fly, you give cloudflare an image link, it transforms, this is what NuxtImage provider `cloudflare`, =>`https://yourdomain.com/cgi/image/w=500/<your_image_link>`
- Images service, you store image in cloudflare, they do pre-tranform (known as transform preset), then serve image => `https://yourdomain.com/imagedelivery/<imageID_that_stored_in_cloudflare>`

In your example, you are using option 2, the Image service, while NuxtImage provider `cloudflare` target option 1

**Comment by Baroshem** [comment] 2024-12-11 11:51
Thanks @phi0411141 I agree with the fact that these are two separate services.

The recommendation with custom provider is a good direction IMO :)

**Comment by MickL** [comment] 2024-12-22 12:12
Currently Nuxt Image only supports transforming images **outside** of Cloudflare Images, see: https://developers.cloudflare.com/images/transform-images/

There is an open feature request to support Cloudflare Images: https://github.com/nuxt/image/issues/427

Also there I posted a provider that you can add to you project that works with Cloudflare Images for me. Hope someone will adapt it to an actual Nuxt Image provider!

Please close this issue in favor of #427

P.S. You guys can also make PRs and changes or add the missing provider, this is an open source project :)

**Comment by MickL** [comment] 2024-12-22 12:31
Currently Nuxt Image only supports transforming images **outside** of Cloudflare Images, see: https://developers.cloudflare.com/images/transform-images/

I agree that the naming is very confusing!

There is an open feature request to support Cloudflare Images: https://github.com/nuxt/image/issues/427

Over there I posted a custom provider that you can add to you project that works with Cloudflare Images. Hope someone will adapt it to an actual Nuxt Image provider :)

@nafiz6629 Please close this issue in favor of #427 (dont forget to upvote)

P.S. You guys can also make PRs and changes or add the missing provider, this is an open source project :)

**Closed** 2024-12-22 13:02 UTC
