### ISSUE TITLE
deployment issue with target static and self hosted images

### ISSUE THREAD

**Issue by lumos94** [nuxt/image#516] opened 2022-06-03 09:31 UTC
Hi @pi0,

Im building a `static` page in nuxtjs. I added the module and set it up according to the instructions in the documentation. (static with self hosted images)

```
ssr:true,
target: 'statics",
 buildModules: [
    // https://go.nuxtjs.dev/vuetify
    '@nuxtjs/vuetify',
    //https://image.nuxtjs.org
     '@nuxt/image'
  ],
```

```
<nuxt-link :to="localePath('/')">
    <nuxt-img
        id="header-logo"
        format="webp"
        src="/logos/logo.png">
   </nuxt-img>
</nuxt-link>
```

When i run `npm run dev` the project compiles but then the development server exists without any errors. 

When I deploy it to the server through github actions the action breaks and exits on `nuxt generate` with the exit code: `/home/githubaction/actions-runner/workspace/_temp/eb47b4c6-6c0d-42cc-[9](https://github.com/xxx/xxxxxx/runs/6722739489?check_suite_focus=true#step:9:10)019-dca85b061dda.sh: line 1: 17085 Segmentation fault      npm run generate
Error: Process completed with exit code 139.`

Any idea why is that?

**Comment by lumos94** [comment] 2022-06-06 10:47
I downgraded to `"@nuxt/image": "0.6.0"` and now the images load correctly. maybe this is a bug with the `0.6.2` version?

**Comment by Baroshem** [comment] 2024-12-02 11:06
Closing as the issue is quite old and the workaround was provided.

**Closed by Baroshem** 2024-12-02 11:06 UTC
