### ISSUE TITLE
ERROR  Cannot find package 'ipx'

### ISSUE THREAD

**Issue by rain-sc** [nuxt/image#1209] opened 2024-01-18 03:12 UTC
Node: 18.8.0
Nuxt: ^3.9.0
Nuxt-Img:  ^1.1.0

 WARN  "ipx" is imported by "node_modules/@nuxt/image/dist/runtime/ipx.mjs", but could not be resolved – treating it as an external dependency.

 ERROR  Cannot find package 'ipx' imported from /vue/.nuxt/prerender/index.mjs

**Comment by pi0** [comment] 2024-01-18 09:19
Can you please provide a reproduction? 🙏🏼

**Comment by JoGlows** [comment] 2024-01-19 02:25
> Hi, I also ran into this error.
> 
> Reproduced with a clean `nuxi init` and `npm i -D @nuxt/image`
> 
> https://github.com/Drew-Macgibbon/cannot-find-ipx-reproduction
> 
> I downgraded to `@nuxt/image@1.2.0` and everything worked fine.

I ran your project and downgraded it will worked. but it can not solve @nuxt/image latest version If I use

**Comment by AloisSeckar** [comment] 2024-01-20 11:01
I can confirm this happens to me too.

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      ssr, devtools, modules, runtimeConfig, image, supabase
- Runtime Modules:  @vueuse/nuxt@10.7.2, @nuxt/image@1.3.0, @nuxtjs/i18n@8.0.0, @nuxtjs/supabase@1.1.5, @nuxtjs/tailwindcss@6.10.4, @formkit/nuxt@1.5.1, @pinia/nuxt@0.5.1
- Build Modules:    -
------------------------------
```

```
  "devDependencies": {
    "@formkit/nuxt": "1.5.1",
    "@nuxt/image": "1.3.0",
    "@nuxtjs/eslint-config-typescript": "12.1.0",
    "@nuxtjs/i18n": "8.0.0",
    "@nuxtjs/supabase": "1.1.5",
    "@nuxtjs/tailwindcss": "6.10.4",
    "@pinia/nuxt": "0.5.1",
    "@vueuse/core": "10.7.2",
    "@vueuse/nuxt": "10.7.2",
    "elrh-pslo": "1.0.1",
    "eslint": "8.56.0",
    "infinitimeline": "0.4.2",
    "nuxt": "3.9.3",
    "openapi-typescript": "5.4.1",
    "pinia": "2.1.7",
    "supabase": "1.131.5",
    "tailwindcss": "3.4.1"
  }
```

Version `1.3.0` is broken, `1.2.0` works

**Comment by zrooda** [comment] 2024-01-21 13:05
Same issue, `1.2.0` works.

**Comment by Drew-Macgibbon** [comment] 2024-01-24 04:02
> I ran your project and downgraded it will worked. but it can not solve @nuxt/image latest version ^1.3.0 If I use

I also faced this error in 3 other projects, `1.3.0` must have introduced some error. Just reverting to `1.2.0` until fixed.

I would be interested to know if using `nuxi add nuxt/image` still causes the issue. I use `npm i` when adding packages.

**Comment by gnidustotalus** [comment] 2024-01-24 21:50
In my case, the solution turned out to be installing a newer version of Node using NVM, specifically upgrading from version 18.16.0 to 18.19.0. Is it possible that the issue was related to the npm cache?

**Comment by Ingramz** [comment] 2024-01-31 12:52
Sharp seems to require node 18.17.0 or newer. https://github.com/lovell/sharp/blob/bd4f1abba28831b8db246366f2f5f8d5ed701eac/package.json#L188-L191

**Comment by SuperNickkk** [comment] 2024-02-03 10:16
I appear to have the same issue.  1.3.0 doesn't work, but 1.2.0 does.

My node version is 20.11.0

**Comment by pauloconnell** [comment] 2024-02-15 00:29
I have the same issue - running node 18.12.1

**Comment by Kheuval** [comment] 2024-02-20 06:39
Hi, I have the same issue.
Node version : 20.10.0
Nuxt version : 3.10.2

1.2.0 works fine but not 1.3.0

**Comment by AloisSeckar** [comment] 2024-02-21 21:46
I encountered this problem again today in my Netlify deplyoment pipeline and it got fixed just by pinning Node version to recent `18.19.1` via [environment variable](https://pratapsharma.com.np/set-node-version-netlify). Didn't have to regress Nuxt Image.

**Comment by tysaner** [comment] 2024-04-02 03:22
I'm getting the same issue with 1.4.0, while I didn't have it with 1.2.0.

Node version : 20.11.1
Nuxt version: 3.11.1

So I downgraded the version of @nuxt/iamge to 1.2

**Comment by davidsandoz** [comment] 2024-04-18 13:53
I'm still getting the error with 1.5.0.

I also noticed that it happens only with `nuxt generate`, not with `nuxt build`.

Downgrading to 1.3.0 makes it work again.

**Comment by davidsandoz** [comment] 2024-04-29 06:37
Thanks, @furkansahintr. However, I don't have `ssr: false` in `nuxt.config`. As I'm doing `nuxt generate`, the website is server-side generated (SSG), and as specified in the documentation page you linked:

> If you are building a static site using `nuxt generate`, Nuxt Image will optimize and save your images locally when your site is generated - and deploy them alongside your generated pages.

Hence, the images should be generated automatically, without the need to specify them in the `nitro.preprender.routes` option. I understand that this would be if one is using Nuxt in SPA mode (not SSR nor SSG).

**Comment by szadave** [comment] 2024-05-29 00:14
**Node Version**: 20.13.1  
**Nuxt Version**: 3.11.2  
**Nuxt Image Version**: 1.7.0
**OS**: Windows: 11 23H2

**Issue**:
After cloning and running `npm install` on a new machine, I encountered this error.

**Additional Information**:
If I run `npm i ipx`, it works, but this is not a clean solution.

**Comment by yxw007** [comment] 2024-07-05 10:58
At present, it seems that only 1.3.0 is a reliable and available version.

**Comment by yxw007** [comment] 2024-07-05 14:36
NuxtImage, I did 2 tests
- Test 1: Create a new nuxt project with integrated @nuxt/image and work (prove: @nuxt/image latest version 1.7.0 is fine)
- Test 2: The existing project integrates @nuxt/image, which cannot be used normally, so I deleted all the node_modules, and found that it works normally after re-clicking pnpm install

Summary: There should be a problem with the installation cache，clear the cache and reinstall it.

**Comment by tedonggo** [comment] 2024-07-21 09:47
"@nuxt/image": "^1.7.0",  still doesn't work 

![image](https://github.com/user-attachments/assets/a0a00d88-db43-47d4-8881-eba3b4e93fb5)

**Comment by tedonggo** [comment] 2024-07-21 09:59
> NuxtImage, I did 2 tests
> 
> * Test 1: Create a new nuxt project with integrated @nuxt/image and work (prove: @nuxt/image latest version 1.7.0 is fine)
> * Test 2: The existing project integrates @nuxt/image, which cannot be used normally, so I deleted all the node_modules, and found that it works normally after re-clicking pnpm install
> 
> Summary: There should be a problem with the installation cache，clear the cache and reinstall it.

Thanks, test2 is useful

**Comment by danielislas3** [comment] 2024-09-08 23:30
Experiencing the same issue. Any help would be appreciated!

**Comment by irorange27** [comment] 2024-10-14 11:53
Also met the issue with, but I have solved

@nuxt/image: 1.8.1
@nuxtjs/color-mode: 6.5.1
nuxt: 3.13.0
ipx: 3.0.1

node: v20.18.0
npm: v10.9.0

Solve it with `rm -r node_modules` and reinstall it.

**Comment by Baroshem** [comment] 2024-12-09 14:01
Closing as the solution was provided.

**Comment by irorange27** [comment] 2024-12-09 14:02
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Closed by Baroshem** 2024-12-09 14:01 UTC
Labels: needs reproduction

**Comment by SuperNickkk** [comment] 2024-12-10 07:42
Thank you all for your input.

I have to say that I long since stopped using Nuxt Image as I started using bash to convert to an appropriate file size and format.

I can't comment on whether newer versions of Nuxt Image solved this problem.  But with 1.3.0 removing nuxt_modules was never the solution.

Someone who is still using Nuxt Image might want to double check this. . .

**Comment by vicXvac** [comment] 2025-02-13 09:57
also was facing a similar issue, was getting this error

ERROR  [worker reload] [worker init] /home/vicafricode/company staff/scupeya-finali/.nuxt/dev/index.mjs failed               11:38:50 AM

  

  [cause]: Cannot find package 'ipx' imported from /home/vicafricode/company staff/scupeya-finali/.nuxt/dev/index.mjs

      at packageResolve (node:internal/modules/esm/resolve:857:9)
      at moduleResolve (node:internal/modules/esm/resolve:926:18)
      at defaultResolve (node:internal/modules/esm/resolve:1056:11)
      at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
      at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
      at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
      at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
      at ModuleJob._link (node:internal/modules/esm/module_job:135:49)


i deleted the node_modules folder and everything was working fine

**Comment by Mugentoki** [comment] 2025-03-05 07:54
I had the same problem, but in my case I had a global version of `libvips` installed via brew which was conflicting with `ipx` module. The funny thing, since `ipx` is listed as as `optionalDependencies`, node simply skipped it without giving any warning.

Deleting the global `libvips` and then reinstalling `node_modules` helped in my case.
In my case it was installed via `brew`.
Check if it's installed: `brew list | grep vips`
Delete it: `brew uninstall libvips`
