### ISSUE TITLE
Prismic provider with netlify

### ISSUE THREAD

**Issue by JosBouma** [nuxt/image#1348] opened 2024-05-02 13:55 UTC
I'm deploying a site to Netlify using Nuxt Image with Prismic as the provider.
In my nuxt config i got:
```
  image: {
    prismic: {}
  },
```

Locally everything (run dev/generate) works as intended and src looks like this:

`https://images.prismic.io/[reponame]/ZjD8LEMTzAJOCcrE_pdf-remotetechteam.png?auto=format,compress`

When i deploy to Netlify the images don't display. On Netlify the src has a relative URL like so:

`/.netlify/images?w=947&h=795&url=https:%2F%2Fimages.prismic.io%2F[reponame]%2FZjD8LEMTzAJOCcrE_pdf-remotetechteam.png?auto=format,compress`

Am I doing something wrong or is this a bug?

**Comment by danielroe** [comment] 2024-05-02 14:06
For now, would you set `provider: 'prismic'` explicitly? It looks like the Netlify environment is overriding your custom provider, which is a bug.

**Comment by JosBouma** [comment] 2024-05-02 14:12
Setting it explicitly like you said fixed the issue, thanks!

```
  image: {
    // prismic: {}
    provider: 'prismic'
  },
```

**Comment by Baroshem** [comment] 2024-12-09 13:50
@lihbr would you be able to take a look at it? :)

**Comment by lihbr** [comment] 2024-12-09 14:06
As Daniel said, I believe Netlify has the default provider defaulting to `ipx`, so setting it to `prismic` instead  will change it.

I'm confused if this is a bug or the intended behavior? ([not sure given the description here](https://image.nuxt.com/get-started/configuration#provider))

**Comment by Baroshem** [comment] 2024-12-12 07:57
Thanks for the comment @lihbr 

I will close this issue then. If the problem still occurs, feel free to reopen it :)

**Closed by Baroshem** 2024-12-12 07:58 UTC
Labels: bug, help wanted
