### ISSUE TITLE
nuxt3 support

### ISSUE THREAD

**Issue by pixelpaulaus** [nuxt/image#453] opened 2021-11-15 07:20 UTC
Hello,
Just checking if any plans on getting this good for nuxt3?

**Comment by productdevbook** [comment] 2021-11-18 18:08
Failed to resolve component: nuxt-img
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Invalid value used as weak map key

**Comment by nathanchase** [comment] 2021-11-20 18:29
Here's a reproduction to use for debugging: https://stackblitz.com/edit/github-cm8nrs-lnkwrm

**Comment by ciaran-io** [comment] 2021-11-27 13:16
Hi, Is there any update or timeline when this module may be supported in Nuxt 3?

**Comment by eMeRiKa13** [comment] 2021-12-11 22:13
I would love to have an answer as well!

**Comment by Baroshem** [comment] 2022-01-04 07:45
I am interested in this module for Nuxt 3 as well. Any plans to make it compatible with the newest version?

**Comment by nandi95** [comment] 2022-01-05 09:47
duplicate of https://github.com/nuxt/image/issues/439

**Comment by OrhanOzkercin** [comment] 2022-01-27 15:45
Any update?

**Comment by mklueh** [comment] 2022-02-16 16:30
> Here's a reproduction to use for debugging: https://stackblitz.com/edit/github-cm8nrs-lnkwrm
> 
> Error:
> 
> ```
> 
>  ERROR  [@nuxt/image] ipx is an optional dependency for local image optimization and is not properly installed. Please try npm install or yarn install again.
> 
> 
>  ERROR  Cannot start nuxt:  Error:                                                                       13:28:47
> Something went wrong installing the "sharp" module
> 
> Cannot find module '../build/Release/sharp-linux-x64.node'
> Require stack:
> - /home/projects/github-cm8nrs-lnkwrm/node_modules/sharp/lib/sharp.js
> - /home/projects/github-cm8nrs-lnkwrm/node_modules/sharp/lib/constructor.js
> - /home/projects/github-cm8nrs-lnkwrm/node_modules/sharp/lib/index.js
> - /home/projects/github-cm8nrs-lnkwrm/node_modules/@nuxt/image/node_modules/ipx/dist/index.cjs
> - /home/projects/github-cm8nrs-lnkwrm/node_modules/@nuxt/image/dist/module.js
> - /home/projects/github-cm8nrs-lnkwrm/index.js
> 
> Possible solutions:
> - Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
> - Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
> - Consult the installation documentation: https://sharp.pixelplumbing.com/install
> 
>   Something went wrong installing the "sharp" module
>   
>   Cannot find module '../build/Release/sharp-linux-x64.node'
>   Require stack:
>   - node_modules/sharp/lib/sharp.js
>   - node_modules/sharp/lib/constructor.js
>   - node_modules/sharp/lib/index.js
>   - node_modules/@nuxt/image/node_modules/ipx/dist/index.cjs
>   - node_modules/@nuxt/image/dist/module.js
>   - index.js
>   
>   Possible solutions:
>   - Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
>   - Install for the current runtime: "npm install --platform=linux --arch=x64 sharp"
>   - Consult the installation documentation: https://sharp.pixelplumbing.com/install
>   at eval (node_modules/@nuxt/image/dist/module.js:132:13)
>   at async Object.ipxSetup [as setup] (node_modules/@nuxt/image/dist/module.js:130:48)
>   at async Object.imageModule2 (node_modules/@nuxt/image/dist/module.js:271:7)
>   at async Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:1351:3)
>   at async initNuxt (node_modules/nuxt3/dist/index.mjs:931:5)
>   at async load (node_modules/nuxi/dist/chunks/dev.mjs:6724:9)
>   at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6763:5)
>   at async _main (node_modules/nuxi/dist/chunks/index.mjs:406:7)
> ```


I'm running into this issue with Nuxt 2. I find it a bit funny that is states that the package is optional, but it fails without it

**Comment by Gyurmatag** [comment] 2022-03-01 11:18
Any update on Nuxt3 support?

**Comment by zynth17** [comment] 2022-03-01 11:22
also waiting for nuxt 3 support

**Comment by jairoblatt** [comment] 2022-03-26 00:03
news?

**Comment by pi0** [comment] 2022-03-28 10:47
Hi everyone. So sorry for the miscommunication about Nuxt 3 support. 

It was a challenging road since we made Nuxt 3 public and we had missing key features to make it happen with proper support of nuxt image with Nuxt 3 and Nitro but we are so close to have them all!

Moving progress to https://github.com/nuxt/image/issues/500. Feel free to subscribe and track progress.

**Closed by pi0** 2022-03-28 10:47 UTC
