### ISSUE TITLE
打包文件出席错误

### ISSUE THREAD

**Issue by zi-jian-a** [nuxt/image#1366] opened 2024-05-21 09:28 UTC
Package import specifier "#internal/nuxt/paths" is not defined in package

**Comment by zi-jian-a** [comment] 2024-05-22 14:57
我明天早上再给您发吧，我这边在休息时间.

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月22日 22:54 |
| 收件人 | nuxt/image ***@***.***> |
| 抄送人 | 郑子健 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [nuxt/image] 打包文件出席错误 (Issue #1366) |

Would you be able to provide a reproduction? 🙏

More info
Why do I need to provide a reproduction?

Reproductions make it possible for us to triage and fix issues quickly with a relatively small team. It helps us discover the source of the problem, and also can reveal assumptions you or we might be making.

What will happen?

If you've provided a reproduction, we'll remove the label and try to reproduce the issue. If we can, we'll mark it as a bug and prioritise it based on its severity and how many people we think it might affect.

If needs reproduction labeled issues don't receive any substantial activity (e.g., new comments featuring a reproduction link), we'll close them. That's not because we don't care! At any point, feel free to comment with a reproduction and we'll reopen it.

How can I create a reproduction?

We have a template for starting with a minimal reproduction:

👉 https://stackblitz.com/github/nuxt/image/tree/main/example

A public GitHub repository is also perfect. 👌

Please ensure that the reproduction is as minimal as possible. See more details in our guide.

You might also find these other articles interesting and/or helpful:

The Importance of Reproductions
How to Generate a Minimal, Complete, and Verifiable Example

**Comment by zi-jian-a** [comment] 2024-05-23 07:52
这个是 执行 npm run build 后生成的文件   其中有 “#internal/nuxt/paths”  再执行 npm run dev  就会报以下错误
 
项目我是从官网的模版中下载的   使用的node版本为20.10.0
在 2024-05-22 22:54:52，"github-actions[bot]" ***@***.***> 写道：

Would you be able to provide a reproduction?

More info
Why do I need to provide a reproduction?

Reproductions make it possible for us to triage and fix issues quickly with a relatively small team. It helps us discover the source of the problem, and also can reveal assumptions you or we might be making.

What will happen?

If you've provided a reproduction, we'll remove the label and try to reproduce the issue. If we can, we'll mark it as a bug and prioritise it based on its severity and how many people we think it might affect.

If needs reproduction labeled issues don't receive any substantial activity (e.g., new comments featuring a reproduction link), we'll close them. That's not because we don't care! At any point, feel free to comment with a reproduction and we'll reopen it.

How can I create a reproduction?

We have a template for starting with a minimal reproduction:

https://stackblitz.com/github/nuxt/image/tree/main/example

A public GitHub repository is also perfect.

Please ensure that the reproduction is as minimal as possible. See more details in our guide.

You might also find these other articles interesting and/or helpful:

The Importance of Reproductions
How to Generate a Minimal, Complete, and Verifiable Example

**Comment by Baroshem** [comment] 2024-12-09 13:48
Closing due to lack of reproduction

**Closed by Baroshem** 2024-12-09 13:48 UTC
Labels: needs reproduction
