### ISSUE TITLE
IPX error in dev server

### ISSUE THREAD

**Issue by estoforshort** [nuxt/image#1444] opened 2024-08-27 14:04 UTC
```json
{
    "error": {
        "message": "[500] [IPX_ERROR] \nSomething went wrong installing the \"sharp\" module\n\nModule did not self-register: '/home/esto/hunters-lodge/node_modules/sharp/build/Release/sharp-linux-x64.node'.\n\nPossible solutions:\n- Using worker threads? See https://sharp.pixelplumbing.com/install#worker-threads\n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"\n- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install"
    }
}
```

Everything works fine when I start up the dev server, but after few hot reloads, it breaks. My environment is very minimal Debian 12 running in WSL2.

**Comment by CommanderStorm** [comment] 2024-08-28 03:31
Duplicate of https://github.com/nuxt/image/issues/1372

Also "My environment is very minimal" is a pretty bad explaiantion on how you if you installed `sharp`, what version of it you are running, what version of `@nuxt/image`, ...

OSS-Support is always just as good as the input you put in..

**Closed** 2024-08-28 04:47 UTC
