### ISSUE TITLE
IPX Error (500)

### ISSUE THREAD

**Issue by standfv** [nuxt/image#518] opened 2022-06-12 02:26 UTC
IPX Error (500): 
Link file image size > 3MB. How to fix it? Thank.

**Comment by pi0** [comment] 2022-06-21 15:11
Hi. I'm trying a [big image](https://images.hdqwalls.com/wallpapers/star-wars-scifi-5k-ss.jpg) (6MB) but cannon t reproduce such error. Can you please provide a reproduction and share format, size and environment you are using?

**Comment by Triloworld** [comment] 2022-06-23 10:11
If there is hidden redirection (non-www to www domain) then you get 500 error.

**Comment by Norbz** [comment] 2023-09-26 13:21
I have the opposite issue, dev mode is fine, I had to rework all my CI because domains and alias are written during build, but now I have an IPX Error 500 once deployed.

no error is being traced in log

**Comment by pi0** [comment] 2023-09-26 16:00
If you have a reproducible project to share, it would greatly help in investigating this issue's root causes.

**Comment by Norbz** [comment] 2024-05-02 14:22
I there. I remember I managed to make it work with a custom provider. The default one wouldn't work for my needs anyway.
Changed job 4 months ago and lost access to the environment I had issues with, so I'm afraid I won't be able to provide any project for you.

**Comment by Baroshem** [comment] 2024-12-02 11:07
Closing due to lack of reproduction.

Feel free to reopen if needed with proper repro :)

**Closed by Baroshem** 2024-12-02 11:07 UTC
Labels: needs reproduction

**Comment by Triloworld** [comment] 2024-12-03 14:47
@Baroshem I wrote reproduction step and isn't there option to have it as repository. 
Create IMG with redirect to ssl will give 500 in dev mode.

"If there is hidden redirection for provided domain (non-www to www domain and same image link) then you get 500 error but on static generation is fine. Only dev mode have problem"
