### ISSUE TITLE
NuxtImg Component Not Rendering in Storybook

### ISSUE THREAD

**Issue by Kingo4luv** [nuxt/image#1023] opened 2023-10-02 11:51 UTC
I am attempting to integrate Storybook with my Nuxt 3 application. While most components render perfectly, I'm facing issues specifically with the NuxtImg component. It works as expected within the Nuxt app, but throws an error when visualized in Storybook.

**Error Message:**

```
[Vue warn]: Component is missing template or render function. 
at <NuxtImg class="w-full h-full object-cover object-center null" alt="Another Night Somewhere in the Universe" provider="imgix" ... >
```
<img width="1792" alt="Screenshot 2023-10-02 at 12 47 02" src="https://github.com/nuxt/image/assets/5897929/33a3080e-a1c5-4951-86d2-9629b56056a3">

**Component Code:**
```
<template>
    <nuxt-img
        class="w-full h-full object-cover object-center"
        :class="`${rounded[radius]} ${imgClass}`"
        :alt="alternateText"
        provider="imgix"
        :src="file.filename"
        :sizes="size"
        loading="lazy"
        :preload="preload"
        :preset="preset"
        @load="$emit('image-loaded')"
    />
</template>
```

**Expected Behavior:**
The NuxtImg component should render without issues in Storybook just as it does within the Nuxt application.

**Actual Behavior:**
The component throws an error and doesn't display as expected.

**Steps to Reproduce:**

Set up a Nuxt 3 project.
Integrate Storybook.
Create a component utilizing NuxtImg.
Attempt to visualize the component in Storybook.
Environment:

Nuxt version: v3.7.3
Nuxt Image verson: v1.0.0-rc.2
Nuxt Storybook version: v7.0.0
Node version: v18.16.0
Browser: Chrome, Firefox, Safari
OS: MacOS, Windows

Additional Notes:
I've followed the recommended configurations for both Nuxt and Storybook.
Other components without NuxtImg seem to render fine in Storybook.
Any assistance on this would be greatly appreciated!

**Comment by perezguedesmaikel** [comment] 2023-12-26 11:17
that happens to me too

**Comment by yuuzora** [comment] 2024-05-03 13:56
Having the same issue

**Comment by Archetipo95** [comment] 2024-05-30 15:16
Take a look here, I mocked the component to show a simple html image

https://github.com/Archetipo95/my-nuxt-starter/blob/main/.storybook/mocks/NuxtImage.ts

**Comment by Baroshem** [comment] 2024-12-10 20:25
Closing as the issue is very old and releates to RC version of the module

**Closed by Baroshem** 2024-12-10 20:25 UTC
