### ISSUE TITLE
Bug: Nuxt prerender generate incorrect url paths

### ISSUE THREAD

**Issue by NanFengCheong** [nuxt/image#921] opened 2023-07-19 15:52 UTC
version: 1.0.0-rc.1
<img width="1065" alt="image" src="https://github.com/nuxt/image/assets/7321833/73346319-d0d2-44fa-bf78-97e184e600b6">
<img width="487" alt="image" src="https://github.com/nuxt/image/assets/7321833/1eaffe66-9437-47b3-9012-76f42cd4058a">

missing addtional "/" for the path.
Reproduction: [Link](https://stackblitz.com/edit/github-9beckd?file=nuxt.config.ts,package.json,app.vue)
nuxt.config.ts
```
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxt/image"],
  image: {
    format: ["avif", "webp"],
    domains: ["i.dummyjson.com"],
  },
})
```

**Comment by Baroshem** [comment] 2024-12-10 20:36
Closing ad the issue is related to RC version.

**Closed by Baroshem** 2024-12-10 20:36 UTC
